interface StructuralNode {
  /**
   * The title of this node as rendered HTML.
   * 
   * @see https://asciidoctor.github.io/asciidoctor.js/master/#abstractblockgettitle
   */
  title: string

  /**
   * The title of this node as plain text.
   */
  titlePlain: string
}

export interface Document extends StructuralNode {}

export interface Section extends StructuralNode {
  /**
   * A normalized form of the ID (generated by this project) that is e.g. used as directory name.
   */
  slug: string

  /**
   * The ID of the section. This is mainly used as the anchor for linking.
   * 
   * @see https://asciidoctor.github.io/asciidoctor.js/master/#abstractnodegetid
   */
  id: string

  /**
   * The type of section, called "section name" by Asciidoctor.
   * 
   * @see https://asciidoctor.github.io/asciidoctor.js/master/#sectiongetsectionname
   */
  sectionType: 'section' | 'appendix'

  /**
   * The 0-based index order of this section within the parent block.
   * 
   * @see https://asciidoctor.github.io/asciidoctor.js/master/#sectiongetindex
   */
  index: number

  /**
   * The caption for this section (only relevant for appendices).
   * 
   * @see https://asciidoctor.github.io/asciidoctor.js/master/#sectiongetcaption
   */
  caption?: string
}
