# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Up to date?

on:
  schedule:
    # Once a day at 5 AM
    - cron: 0 5 * * *
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run clone
    - run: npm run update
    - run: bash ./verify-no-changes.sh
